<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_rak extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Tbl_rak_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->uri->segment(3));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . '.php/c_url/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'index.php/tbl_rak/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'index.php/tbl_rak/index/';
            $config['first_url'] = base_url() . 'index.php/tbl_rak/index/';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = FALSE;
        $config['total_rows'] = $this->Tbl_rak_model->total_rows($q);
        $tbl_rak = $this->Tbl_rak_model->get_limit_data($config['per_page'], $start, $q);
        $config['full_tag_open'] = '<ul class="pagination pagination-sm no-margin pull-right">';
        $config['full_tag_close'] = '</ul>';
        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'tbl_rak_data' => $tbl_rak,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->template->load('template','tbl_rak/tbl_rak_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Tbl_rak_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_rak' => $row->id_rak,
		'nama_rak' => $row->nama_rak,
	    );
            $this->template->load('template','tbl_rak/tbl_rak_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tbl_rak'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('tbl_rak/create_action'),
	    'id_rak' => set_value('id_rak'),
	    'nama_rak' => set_value('nama_rak'),
	);
        $this->template->load('template','tbl_rak/tbl_rak_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_rak' => $this->input->post('nama_rak',TRUE),
	    );

            $this->Tbl_rak_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('tbl_rak'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tbl_rak_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('tbl_rak/update_action'),
		'id_rak' => set_value('id_rak', $row->id_rak),
		'nama_rak' => set_value('nama_rak', $row->nama_rak),
	    );
            $this->template->load('template','tbl_rak/tbl_rak_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tbl_rak'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_rak', TRUE));
        } else {
            $data = array(
		'nama_rak' => $this->input->post('nama_rak',TRUE),
	    );

            $this->Tbl_rak_model->update($this->input->post('id_rak', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('tbl_rak'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tbl_rak_model->get_by_id($id);

        if ($row) {
            $this->Tbl_rak_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('tbl_rak'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tbl_rak'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_rak', 'nama rak', 'trim|required');

	$this->form_validation->set_rules('id_rak', 'id_rak', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Tbl_rak.php */
/* Location: ./application/controllers/Tbl_rak.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-06-19 20:42:22 */
/* http://harviacode.com */